### ISSUE TITLE
aptly crashing

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga-packaging#11]
Under investigation...

Currently open: https://github.com/smira/aptly/issues/582

Also: https://github.com/smira/aptly/issues/431

**Comment by lazyfrosch** [comment]
New interesting crash:

```
Jun 13 07:05:15 icinga-aptly aptly[13046]: panic: (*context.FatalError) (0xaf5b60,0xc420220000)
Jun 13 07:05:15 icinga-aptly aptly[13046]: goroutine 7 [running]:
Jun 13 07:05:15 icinga-aptly aptly[13046]: github.com/smira/aptly/context.Fatal(0xfd1340, 0xc4201c9210)
Jun 13 07:05:15 icinga-aptly aptly[13046]: /Users/smira/Documents/go/src/github.com/smira/aptly/context/context.go:64 +0xcc
Jun 13 07:05:15 icinga-aptly aptly[13046]: github.com/smira/aptly/context.(*AptlyContext).CollectionFactory(0xc4201ab600, 0x0)
Jun 13 07:05:15 icinga-aptly aptly[13046]: /Users/smira/Documents/go/src/github.com/smira/aptly/context/context.go:294 +0x19b
Jun 13 07:05:15 icinga-aptly aptly[13046]: github.com/smira/aptly/api.flushColections()
Jun 13 07:05:15 icinga-aptly aptly[13046]: /Users/smira/Documents/go/src/github.com/smira/aptly/api/api.go:34 +0x31
Jun 13 07:05:15 icinga-aptly aptly[13046]: github.com/smira/aptly/api.acquireDatabase(0xc420011260, 0xc4200112c0)
Jun 13 07:05:15 icinga-aptly aptly[13046]: /Users/smira/Documents/go/src/github.com/smira/aptly/api/api.go:94 +0x80
Jun 13 07:05:15 icinga-aptly aptly[13046]: created by github.com/smira/aptly/api.Router
Jun 13 07:05:15 icinga-aptly aptly[13046]: /Users/smira/Documents/go/src/github.com/smira/aptly/api/router.go:26 +0x196
Jun 13 07:05:15 icinga-aptly systemd[1]: aptly-api.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by lazyfrosch** [comment]
Looks like the crashes tend to happen during our `db cleanup` every hour.

See upstream issue.

**Comment by lazyfrosch** [comment]
Upstream has reworked database connections: https://github.com/smira/aptly/pull/589

For now we are pretty fine with the nightly build, running cleanups only once a day.

We should update to 1.1.0 when its available...

**Comment by lazyfrosch** [comment]
We never saw this error again :smile:
