### ISSUE TITLE
fontello-ifont config.json not installed

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga-packaging#4]
When accessing `icingaweb2/doc/style/font` to check supported icons in icingaweb2, the following error appears:

```
file_get_contents(/usr/share/icingaweb2/application/fonts/fontello-ifont/config.json): failed to open stream: No such file or directory

#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'file_get_conten...', '/usr/share/icin...', 21, Array)
#1 /usr/share/icingaweb2/modules/doc/application/controllers/StyleController.php(21): file_get_contents('/usr/share/icin...')
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Doc\Controllers\StyleController->fontAction()
#3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('fontAction')
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#7 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#8 {main}
```

We don't install `application/fonts/fontello-ifont/config.json` into the Debian packages right now.

Originally raised in https://github.com/Icinga/icingaweb2/issues/2764

**Comment by lazyfrosch** [comment]
Will be included in icingaweb2-2.4.2-1
